name: sb-debezium-demo
services:
  access-svc:
    depends_on:
      - database
    build:
      context: ../..
      dockerfile: ./src/docker/Dockerfile
      args:
        MODULE: sb-access-service
    ports:
        - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/sb_access
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root

  access-monitor:
    depends_on:
      - database
      - access-svc
    build:
      context: ../..
      dockerfile: ./src/docker/Dockerfile
      args:
        MODULE: sb-access-monitor
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DEBEZIUM_PROPERTIES_DATABASE_HOSTNAME: database
      DEBEZIUM_PROPERTIES_DATABASE_PORT: 5432
      DEBEZIUM_PROPERTIES_DATABASE_USER: root
      DEBEZIUM_PROPERTIES_DATABASE_PASSWORD: root
      DEBEZIUM_PROPERTIES_DATABASE_DBNAME: sb_access

  database:
    image: quay.io/debezium/postgres:16-alpine
    ports:
        - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "sb_access" ]
      interval: 30s
      timeout: 60s
      retries: 5
    environment:
        POSTGRES_DB: sb_access
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root

